# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR pyLoad Team
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pyLoad 0.4.4\n"
"Report-Msgid-Bugs-To: 'bugs@pyload.org'\n"
"POT-Creation-Date: 2011-01-05 20:16+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: pyLoadCore.py:174
msgid "Received Quit signal"
msgstr ""

#: pyLoadCore.py:259
#, python-format
msgid "pyLoad already running with pid %s"
msgstr ""

#: pyLoadCore.py:273
#, python-format
msgid "Failed changing group: %s"
msgstr ""

#: pyLoadCore.py:282
#, python-format
msgid "Failed changing user: %s"
msgstr ""

#: pyLoadCore.py:284
msgid "folder for logs"
msgstr ""

#: pyLoadCore.py:295
#, python-format
msgid "Using home directory: %s"
msgstr ""

#: pyLoadCore.py:301
msgid "pycrypto to decode container files"
msgstr ""

#: pyLoadCore.py:304
msgid "Django for webinterface"
msgstr ""

#: pyLoadCore.py:305
msgid "folder for temporary files"
msgstr ""

#: pyLoadCore.py:310
msgid "folder for downloads"
msgstr ""

#: pyLoadCore.py:311
msgid "file for links"
msgstr ""

#: pyLoadCore.py:314
msgid "OpenSSL for secure connection"
msgstr ""

#: pyLoadCore.py:337
#, python-format
msgid "Downloadtime: %s"
msgstr ""

#: pyLoadCore.py:348
#, python-format
msgid "Free space: %sGB"
msgstr ""

#: pyLoadCore.py:350
#, python-format
msgid "Free space: %sMB"
msgstr ""

#: pyLoadCore.py:379
msgid "restarting pyLoad"
msgstr ""

#: pyLoadCore.py:383
msgid "pyLoad quits"
msgstr ""

#: pyLoadCore.py:399
msgid "Secure XMLRPC Server Started"
msgstr ""

#: pyLoadCore.py:401
msgid "SSL Certificates not found, fallback to auth XMLRPC server"
msgstr ""

#: pyLoadCore.py:403 pyLoadCore.py:406
msgid "Auth XMLRPC Server Started"
msgstr ""

#: pyLoadCore.py:412
#, python-format
msgid "Failed starting XMLRPC server CLI and GUI will not be available: %s"
msgstr ""

#: pyLoadCore.py:456
#, python-format
msgid "Install %s"
msgstr ""

#: pyLoadCore.py:491
#, python-format
msgid "could not find %(desc)s: %(name)s"
msgstr ""

#: pyLoadCore.py:493
#, python-format
msgid "could not create %(desc)s: %(name)s"
msgstr ""

#: pyLoadCore.py:518
msgid "shutting down..."
msgstr ""

#: pyLoadCore.py:533
msgid "error while shutting down"
msgstr ""

#: pyLoadCore.py:672
#, python-format
msgid "Added package %(name)s containing %(count)d links"
msgstr ""

#: pyLoadCore.py:724
#, python-format
msgid "Added %(count)d links to package #%(package)d "
msgstr ""

#: pyLoadCore.py:918
msgid "killed pyLoad from Terminal"
msgstr ""

#: module/JsEngine.py:89
msgid ""
"No js engine detected, please install either Spidermonkey, ossp-js or pyv8"
msgstr ""

#: module/ThreadManager.py:94
#, python-format
msgid "Reconnect Failed: %s"
msgstr ""

#: module/ThreadManager.py:118
msgid "Reconnect script not found!"
msgstr ""

#: module/ThreadManager.py:124
msgid "Starting reconnect"
msgstr ""

#: module/ThreadManager.py:134
#, python-format
msgid "Old IP: %s"
msgstr ""

#: module/ThreadManager.py:139
msgid "Failed executing reconnect script!"
msgstr ""

#: module/ThreadManager.py:151
#, python-format
msgid "Reconnected, new IP: %s"
msgstr ""

#: module/HookManager.py:50
#, python-format
msgid "Error executing hooks: %s"
msgstr ""

#: module/HookManager.py:64
#, python-format
msgid "%(name)s loaded, activated %(value)s"
msgstr ""

#: module/HookManager.py:66
#, python-format
msgid "Failed activating %(name)s"
msgstr ""

#: module/FileDatabase.py:58
msgid "finished"
msgstr ""

#: module/FileDatabase.py:58
msgid "offline"
msgstr ""

#: module/FileDatabase.py:58
msgid "online"
msgstr ""

#: module/FileDatabase.py:58
msgid "queued"
msgstr ""

#: module/FileDatabase.py:58
msgid "checking"
msgstr ""

#: module/FileDatabase.py:58
msgid "waiting"
msgstr ""

#: module/FileDatabase.py:58
msgid "reconnected"
msgstr ""

#: module/FileDatabase.py:58
msgid "starting"
msgstr ""

#: module/FileDatabase.py:58
msgid "failed"
msgstr ""

#: module/FileDatabase.py:58
msgid "aborted"
msgstr ""

#: module/FileDatabase.py:58
msgid "decrypting"
msgstr ""

#: module/FileDatabase.py:58
msgid "custom"
msgstr ""

#: module/FileDatabase.py:58
msgid "downloading"
msgstr ""

#: module/FileDatabase.py:58
msgid "processing"
msgstr ""

#: module/FileDatabase.py:58
msgid "unknown"
msgstr ""

#: module/FileDatabase.py:493 module/plugins/hooks/IRCInterface.py:68
#: module/plugins/hooks/XMPPInterface.py:75
#, python-format
msgid "Package finished: %s"
msgstr ""

#: module/FileDatabase.py:607
msgid "Filedatabase was deleted due to incompatible version."
msgstr ""

#: module/PluginThread.py:159
#, python-format
msgid "Download skipped: %(name)s @ %(plugin)s"
msgstr ""

#: module/PluginThread.py:162
msgid "File already exists."
msgstr ""

#: module/PluginThread.py:165
#, python-format
msgid "Download starts: %s"
msgstr ""

#: module/PluginThread.py:173 module/PluginThread.py:321
#, python-format
msgid "Plugin %s is missing a function."
msgstr ""

#: module/PluginThread.py:180 module/PluginThread.py:232
#: module/PluginThread.py:340
#, python-format
msgid "Download aborted: %s"
msgstr ""

#: module/PluginThread.py:197
#, python-format
msgid "Download restarted: %s"
msgstr ""

#: module/PluginThread.py:207 module/PluginThread.py:330
#, python-format
msgid "Download is offline: %s"
msgstr ""

#: module/PluginThread.py:210 module/PluginThread.py:253
#, python-format
msgid "Download failed: %(name)s | %(msg)s"
msgstr ""

#: module/PluginThread.py:224
msgid ""
"Couldn't connect to host or connection resetted waiting 1 minute and retry."
msgstr ""

#: module/PluginThread.py:269
#, python-format
msgid "Download finished: %s"
msgstr ""

#: module/PluginThread.py:316
#, python-format
msgid "Decrypting starts: %s"
msgstr ""

#: module/PluginThread.py:333 module/PluginThread.py:354
#, python-format
msgid "Decrypting failed: %(name)s | %(msg)s"
msgstr ""

#: module/PluginThread.py:347
#, python-format
msgid "Retrying %s"
msgstr ""

#: module/web/ServerThread.py:45
msgid "Database for Webinterface does not exitst, it will not be available."
msgstr ""

#: module/web/ServerThread.py:46
msgid "Please run: python pyLoadCore.py -s"
msgstr ""

#: module/web/ServerThread.py:47
msgid ""
"Go through the setup and create a database and add an user to gain access."
msgstr ""

#: module/web/ServerThread.py:88
msgid "SSL certificates not found."
msgstr ""

#: module/web/ServerThread.py:98
#, python-format
msgid ""
"Can't use %(server)s, either python-flup or %(server)s is not installed!"
msgstr ""

#: module/web/ServerThread.py:132
#, python-format
msgid "Starting nginx Webserver: %(host)s:%(port)d"
msgstr ""

#: module/web/ServerThread.py:169
#, python-format
msgid "Starting lighttpd Webserver: %(host)s:%(port)d"
msgstr ""

#: module/web/ServerThread.py:179
#, python-format
msgid "Starting django builtin Webserver: %(host)s:%(port)d"
msgstr ""

#: module/plugins/Crypter.py:63
#, python-format
msgid "Parsed package %(name)s with %(len)d links"
msgstr ""

#: module/plugins/Plugin.py:262
msgid ""
"Pil and tesseract not installed and no Client connected for captcha "
"decrypting"
msgstr ""

#: module/plugins/Plugin.py:264
msgid "No Client connected for captcha decrypting"
msgstr ""

#: module/plugins/Plugin.py:327 module/plugins/Plugin.py:353
#, python-format
msgid "Setting User and Group failed: %s"
msgstr ""

#: module/plugins/Container.py:71
msgid "File not exists."
msgstr ""

#: module/plugins/PluginManager.py:73
msgid "Crypter"
msgstr ""

#: module/plugins/PluginManager.py:74
msgid "Container"
msgstr ""

#: module/plugins/PluginManager.py:75
msgid "Hoster"
msgstr ""

#: module/plugins/PluginManager.py:77
msgid "Captcha"
msgstr ""

#: module/plugins/PluginManager.py:78
msgid "Account"
msgstr ""

#: module/plugins/PluginManager.py:79
msgid "Hook"
msgstr ""

#: module/plugins/PluginManager.py:81
msgid "created index of plugins"
msgstr ""

#: module/plugins/PluginManager.py:163
#, python-format
msgid "%s has a invalid pattern."
msgstr ""

#: module/plugins/PluginManager.py:290
#, python-format
msgid "Error importing %(name)s: %(msg)s"
msgstr ""

#: module/plugins/PluginManager.py:291
msgid "You should fix dependicies or deactivate load on startup."
msgstr ""

#: module/plugins/AccountManager.py:84
msgid "Account settings deleted, due to new config format."
msgstr ""

#: module/plugins/Account.py:51 module/plugins/Account.py:55
#, python-format
msgid "Could not login with %(plugin)s account %(user)s | %(msg)s"
msgstr ""

#: module/plugins/Account.py:51
msgid "Wrong Password"
msgstr ""

#: module/plugins/Account.py:159
#, python-format
msgid "Your Time %s has wrong format, use: 1:22-3:44"
msgstr ""

#: module/plugins/Account.py:196
#, python-format
msgid ""
"%(plugin)s Account %(user)s has not enough traffic, checking again in 30min"
msgstr ""

#: module/plugins/Account.py:202
#, python-format
msgid "%(plugin)s Account %(user)s is expired, checking again in 1h"
msgstr ""

#: module/plugins/crypter/SerienjunkiesOrg.py:115
msgid "Downloadlimit reached"
msgstr ""

#: module/plugins/crypter/CryptItCom.py:40
msgid "File not found"
msgstr ""

#: module/plugins/hooks/ClickAndLoad.py:73
msgid "Click'N'Load: Port 9666 already in use"
msgstr ""

#: module/plugins/hooks/UnRar.py:119
#, python-format
msgid "starting Unrar of %s"
msgstr ""

#: module/plugins/hooks/UnRar.py:137 module/plugins/hooks/UnRar.py:168
#, python-format
msgid "Unrar of %s failed (wrong password)"
msgstr ""

#: module/plugins/hooks/UnRar.py:143
#, python-format
msgid "Unrar of %s failed (missing volume)"
msgstr ""

#: module/plugins/hooks/UnRar.py:147 module/plugins/hooks/UnRar.py:164
#, python-format
msgid "Unrar of %s ok"
msgstr ""

#: module/plugins/hooks/UnRar.py:152 module/plugins/hooks/UnRar.py:160
#, python-format
msgid "Unrar of %s failed"
msgstr ""

#: module/plugins/hooks/UnRar.py:155
#, python-format
msgid ""
"Your ram amount of %s MB seems not sufficient to unrar this file. You can "
"deactivate this warning and risk instability"
msgstr ""

#: module/plugins/hooks/IRCInterface.py:75
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s "
msgstr ""

#: module/plugins/hooks/XMPPInterface.py:82
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s"
msgstr ""

#: module/plugins/hooks/HotFolder.py:82
#, python-format
msgid "Added %s from HotFolder"
msgstr ""

#: module/plugins/hooks/ExternalScripts.py:48
#: module/plugins/hooks/ExternalScripts.py:49
msgid "folders for scripts"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:43
msgid "*** Plugins have been updated, please restart pyLoad ***"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:45
msgid "No plugin updates available"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:53
msgid "No Updates for pyLoad"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:56
#, python-format
msgid "***  New pyLoad Version %s available  ***"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:57
msgid "***  Get it here: http://pyload.org/download  ***"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:60
#: module/plugins/hooks/UpdateManager.py:70
msgid "Not able to connect server for updates"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:95
#, python-format
msgid "New version of %(type)s|%(name)s : %(version).2f"
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:93
#, python-format
msgid "Megaupload: waiting %d minutes"
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:110
msgid "You need premium to download files larger than 1 GB"
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:115
msgid "The file is password protected, enter a password and restart."
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:132
msgid "Megaupload is currently blocking your IP. Try again later, manually."
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:204
msgid ""
"Looks like the file is still not available. Retry downloading later, "
"manually."
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:207
msgid "Wrong password for download link."
msgstr ""

#: module/plugins/hoster/UploadedTo.py:57
#: module/plugins/hoster/RapidshareCom.py:139
#, python-format
msgid "%(name)s: Use Premium Account (%(left)sGB left)"
msgstr ""

#: module/plugins/hoster/UploadedTo.py:59
#: module/plugins/hoster/RapidshareCom.py:141
#, python-format
msgid "%s: Not enough traffic left"
msgstr ""

#: module/plugins/hoster/UploadedTo.py:62
msgid "Traffic exceeded"
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:99
msgid "Rapidshare: Traffic Share (direct download)"
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:129
#: module/plugins/hoster/RapidshareCom.py:199
msgid "Already downloading from this ip address, waiting 60 seconds"
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:133
msgid "Invalid Auth Code, download will be restarted"
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:203
msgid "RapidShareCom: No free slots"
msgstr ""

#: module/plugins/hoster/FilesMailRu.py:91
msgid "There was HTML Code in the Downloaded File("
msgstr ""

#: module/plugins/hoster/NetloadIn.py:169
#, python-format
msgid "Netload: waiting between downloads %d s."
msgstr ""

#: module/plugins/hoster/NetloadIn.py:199
#, python-format
msgid "Netload: waiting for captcha %d s."
msgstr ""

#: module/plugins/hoster/NetloadIn.py:238
msgid "Downloaded File was empty"
msgstr ""

#: module/plugins/container/LinkList.py:54
msgid "LinkList could not be cleared."
msgstr ""

#: module/plugins/accounts/MegauploadCom.py:43
msgid "Activate direct Download in your MegaUpload Account"
msgstr ""
